apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverless-hpa
spec:
  selector:
    matchLabels:
      app: hpa
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: hpa
    spec:
      containers:
      - name: hpa
        image: docker.io/summerlmm/serverless-hpa
        ports:
        - containerPort: 8000
